### ISSUE TITLE
Dockercontaier für Linux - Hotwo?

### ISSUE THREAD

**Issue by smileyman-1** [zivillian/ora2mqtt#14]
In Windows läuft ora2mqtt perfekt - Danke für die klasse Entwicklung.

Leider bekomme ich es in einem Docker-Container nicht zum laufen. - Kann mir da jemand bitte einen Tipp geben?
Welche Schritte müssen in portainer (läuft bei mir auf Basis von Debian, ARM) durchgeführt werden, dass ich den Container zum Laufen bekomme?

Danke für einen Tipp.

**Comment by SvenAbels** [comment]
Ich nutze zwar kein Portainer, aber ich starte das Projekt  unter Linux mit folgendem Befehl:

`#!/bin/bash
docker run -itd \
--name=ora2mqtt \
--restart=always \
-e TZ=Europe/Berlin \
--net=host \
-v /home/XXXX/docker/ora-mqtt/ora2mqtt.yml:/config/ora2mqtt.yml \
zivillian/ora2mqtt:latest
`

**Comment by smileyman-1** [comment]
Top - du hast recht. Ich habe offenbar den Baum vor lauter Bäumen nicht gesehen.
Der Befehl steht ja auch so weitgehend in der Readme.
Vielen Dank für den Tipp.

**Comment by zivillian** [comment]
Der Vollständigkeit halber hier meine Portainer config:
```yaml
version: '3'
services:
  ora2mqtt:
    image: zivillian/ora2mqtt:main
    restart: unless-stopped
    volumes:
      - config:/config

volumes:
  config:
```

Die ora2mqtt.yml muss dann im config Ordner liegen (bei mir `/var/lib/docker/volumes/ora2mqtt_config/_data/ora2mqtt.yml`).
