### ISSUE TITLE
Complete newbie

### ISSUE THREAD

**Issue by Dieseldog57** [zivillian/ora2mqtt#31]
Hi there, im a complete newbie, well I say complete, but I do run Proxmox on a home server and im keen to learn. I have a ORA and want to install this, would anyone be so kind as to walk me through it in a simple way?? Many thanks in advance.

**Comment by smileyman-1** [comment]
Suggestion: test it first on the command line in Windows. - This is the easiest way. Here you also create the config file that you will later use for the container.
If that works, you can switch to Docker and Co.

**Comment by Dieseldog57** [comment]
I don't suppose you have a guide for that do you, im still learning, sorry.

**Comment by Dieseldog57** [comment]
Hiya, I’m back trying again. 

- I have created the ora2mqtt.yml file on a windows pc
- i am running a vm in proxmox (Ubuntu server) and have docker + portainer installed.
- i have the docker image installed but it keeps flagging up it cant find the ora2mqtt.yml file. How do I transfer this and where do I transfer it too?? 

Kindest regards

Jamie

**Comment by zivillian** [comment]
You need to mount a volume to provide the config. This was my stack config in portainer:
```yaml
version: '3' 
services: 
  ism7: 
    image: zivillian/ora2mqtt:main
    restart: unless-stopped
    volumes:
      - config:/config

volumes:
  config:
```

The yaml file then goes in to the docker volume at `/var/lib/docker/volumes/<stackname>_config/_data/`.
