### ISSUE TITLE
2041142 - Ladevorgang 

### ISSUE THREAD

**Issue by jmerifjKriwe** [zivillian/ora2mqtt#34]
Kann es sein, dass 2041142 eher für sowas wie "Ladestecker eingesteckt" steht?
Bei mir steht der die e ganze Zeit auf 1, obwohl nur die WB verbunden ist, aber derzeit (weil zu wenig PV Leistung) nicht geladen wird. 
Sollte dem so sein, wäre die Frage, wo sich das echte "Ladevorgang läuft" versteckt.

Kann man im MQTT Explorer die Veränderungen der Werte in den Topics irgendwie ünersichtlicher anzeigen lassen als das man jedes Topic extra anklicken und die Historie aufrufen muss?
Dann könnte man gezielter auf die Suche gehen - auch nach sowas wie der aktuellen Ladegeschwindigkeit.

**Comment by daemonenstall** [comment]
Nein, der Sensor berücksichtigt wirklich ob geladen wird oder nicht. Hat nichts mit an- oder abgesteckt zu tun.

So schaut mein Sensor in HASS dafür aus:
```
- binary_sensor:
    - name: "Ladevorgang Ora"
      unique_id: a5c45fa3-91f9-45c4-b578-6ae59dcf610c
      state_topic: "GWM/ADJUST_THIS/status/items/2041142/value"
      payload_off: "0"
      payload_on: "1"
      value_template: "{{ value }}"
      device_class: battery_charging
```
Das ist der Sensor:
![grafik](https://github.com/user-attachments/assets/9104eb26-850e-4231-aa32-3bf70b705618)
Das ist die Leistung der Wallbox:
![grafik](https://github.com/user-attachments/assets/42ef4385-9edb-4647-9e2c-84535d47d8df)
